[package]
name = "bissel"
version = "0.2.0"
description = "Robotics-focused publish/request middleware for embedded Linux"
authors = ["Christopher Moran <christopher.and.moran@gmail.com>"]
edition = "2018"
license = "LGPL-3.0"
repository = "https://github.com/quietlychris/bissel"
keywords = ["robotics", "middleware", "autonomy"]

[workspace]
members = ["crates/*", "bin/*"]

[features]
dynamic = ["bissel_dylib"]

[dependencies]
bissel_std = {path = "crates/bissel_std", version = "0.2.0"}
bissel_dylib = {path = "crates/bissel_dylib", version = "0.2.0", optional = true}

[dev-dependencies]
serde = {version = "1", default-features = false, features = ["derive"]}
tracing-subscriber = "0.3"
tracing-appender = "0.2"
postcard = {version = "0.7", features = ["alloc"]}

[[example]]
name = "host_and_single_node"
path = "examples/host_and_single_node.rs"

[[example]]
name = "simple_host"
path = "examples/simple_host.rs"

[[example]]
name = "simple_node"
path = "examples/simple_node.rs"

[[example]]
name = "multiple_nodes"
path = "examples/multiple_nodes.rs"
