name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v2
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    - name: Maturin
      run: apt-get install python-pip
    - name: Maturin
      run: pip install maturin
    - name: Install cargo-deny
      run: cargo install --locked cargo-deny
    - name: Default CI
      run: cargo run -p ci
    - name: QUIC CI
      run: cargo run -p ci --features quic
