name: CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v2
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    - name: Default CI
      run: cargo run -p ci
    - name: QUIC CI
      run: cargo run -p ci --features quic
  
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: stable
      
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 -- --test-threads=1
    